/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelbookingsystem48;

/**
 *
 * @author jeff-pc
 */
public class MainView extends View {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnViewHotel = new javax.swing.JButton();
        btnViewRoom = new javax.swing.JButton();
        btnViewCustomer = new javax.swing.JButton();
        btnViewGuest = new javax.swing.JButton();
        btnViewMembership = new javax.swing.JButton();
        btnViewBooking = new javax.swing.JButton();
        btnViewPayment = new javax.swing.JButton();
        btnExitSystem = new javax.swing.JButton();
        btnViewAbout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Heavenly Group E HBS");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnViewHotel.setText("Hotel Management");
        btnViewHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewHotelActionPerformed(evt);
            }
        });

        btnViewRoom.setText("Room Management");
        btnViewRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRoomActionPerformed(evt);
            }
        });

        btnViewCustomer.setText("Customer Management");
        btnViewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCustomerActionPerformed(evt);
            }
        });

        btnViewGuest.setText("Guest Management");
        btnViewGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewGuestActionPerformed(evt);
            }
        });

        btnViewMembership.setText("Membership Management");
        btnViewMembership.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMembershipActionPerformed(evt);
            }
        });

        btnViewBooking.setText("Booking Management");
        btnViewBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBookingActionPerformed(evt);
            }
        });

        btnViewPayment.setText("Payment Management");
        btnViewPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPaymentActionPerformed(evt);
            }
        });

        btnExitSystem.setText("Exit");
        btnExitSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitSystemActionPerformed(evt);
            }
        });

        btnViewAbout.setText("About System");
        btnViewAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAboutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExitSystem))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnViewRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(btnViewHotel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewGuest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnViewAbout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewMembership, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewHotel)
                    .addComponent(btnViewMembership))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewRoom)
                    .addComponent(btnViewBooking))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewCustomer)
                    .addComponent(btnViewPayment))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewGuest)
                    .addComponent(btnViewAbout))
                .addGap(18, 18, 18)
                .addComponent(btnExitSystem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitSystemActionPerformed
        // TODO add your handling code here:
        if(super.getController().getSysModel().closeConnection()){
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitSystemActionPerformed

    private void btnViewHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewHotelActionPerformed
        // TODO add your handling code here:
        getController().setView(new HotelView(), this);
    }//GEN-LAST:event_btnViewHotelActionPerformed

    private void btnViewRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRoomActionPerformed
        // TODO add your handling code here:
        getController().setView(new RoomView(), this);
    }//GEN-LAST:event_btnViewRoomActionPerformed

    private void btnViewCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCustomerActionPerformed
        // TODO add your handling code here:
        getController().setView(new CustomerView(), this);
    }//GEN-LAST:event_btnViewCustomerActionPerformed

    private void btnViewGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewGuestActionPerformed
        // TODO add your handling code here:
        getController().setView(new GuestView(), this);
    }//GEN-LAST:event_btnViewGuestActionPerformed

    private void btnViewMembershipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMembershipActionPerformed
        // TODO add your handling code here:
        getController().setView(new MembershipView(), this);
    }//GEN-LAST:event_btnViewMembershipActionPerformed

    private void btnViewBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBookingActionPerformed
        // TODO add your handling code here:
        getController().setView(new BookingView(), this);
    }//GEN-LAST:event_btnViewBookingActionPerformed

    private void btnViewPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPaymentActionPerformed
        // TODO add your handling code here:
        getController().setView(new PaymentView(), this);
    }//GEN-LAST:event_btnViewPaymentActionPerformed

    private void btnViewAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAboutActionPerformed
        // TODO add your handling code here:
        getController().setView(new AboutView(), this);
    }//GEN-LAST:event_btnViewAboutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExitSystem;
    private javax.swing.JButton btnViewAbout;
    private javax.swing.JButton btnViewBooking;
    private javax.swing.JButton btnViewCustomer;
    private javax.swing.JButton btnViewGuest;
    private javax.swing.JButton btnViewHotel;
    private javax.swing.JButton btnViewMembership;
    private javax.swing.JButton btnViewPayment;
    private javax.swing.JButton btnViewRoom;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
