/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelbookingsystem48;


import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
import javax.swing.JTextField;


/**
 * This is the Room view for the hotel booking system.
 * 
 * @author Jeffrey Middendorf
 * @version 1.0
 * @since 2/4/2017
 */
public class RoomView extends View {

    String actionType;
    
    /**
     * Creates new form RoomView
     */
    public RoomView() {
        initComponents();
        //populateComboBox();
        setSubFormVisibility(false);
        actionType = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblResults = new javax.swing.JTable();
        btnCreate = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        cboFacilityId = new javax.swing.JComboBox<>();
        btnFindByType = new javax.swing.JButton();
        lblSearchCombo = new javax.swing.JLabel();
        lblSearchID = new javax.swing.JLabel();
        txtActionID = new javax.swing.JTextField();
        txtRoomNumber = new javax.swing.JTextField();
        lblRoomNumber = new javax.swing.JLabel();
        lblHotelId = new javax.swing.JLabel();
        lblRoomType = new javax.swing.JLabel();
        txtRoomType = new javax.swing.JTextField();
        btnCommitUpdate = new javax.swing.JButton();
        btnDeleteRecord = new javax.swing.JButton();
        txtRoomPrice = new javax.swing.JTextField();
        lblRoomPrice = new javax.swing.JLabel();
        txtRoomDescription = new javax.swing.JTextField();
        lblRoomDescription = new javax.swing.JLabel();
        txtMaxOccupancy = new javax.swing.JTextField();
        lblMaxOccupancy = new javax.swing.JLabel();
        btnFindAction = new javax.swing.JButton();
        btnCreateCommit = new javax.swing.JButton();
        cboHotelId = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Room Number", "Hotel ID", "Type", "Price", "Description", "Max Occupancy"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblResults.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblResults);

        btnCreate.setText("Create A Room");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update a Room");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete a Room");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSearch.setText("Read Room");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnReturn.setText("Return");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        cboFacilityId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnFindByType.setText("Find");
        btnFindByType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindByTypeActionPerformed(evt);
            }
        });

        lblSearchCombo.setLabelFor(cboFacilityId);
        lblSearchCombo.setText("Facility");

        lblSearchID.setLabelFor(txtActionID);
        lblSearchID.setText("Enter ID");

        txtRoomNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoomNumberActionPerformed(evt);
            }
        });

        lblRoomNumber.setLabelFor(txtRoomNumber);
        lblRoomNumber.setText("Room Numer");

        lblHotelId.setText("Hotel ID");

        lblRoomType.setLabelFor(txtRoomType);
        lblRoomType.setText("Room Type");

        btnCommitUpdate.setText("Update");
        btnCommitUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommitUpdateActionPerformed(evt);
            }
        });

        btnDeleteRecord.setBackground(new java.awt.Color(255, 0, 0));
        btnDeleteRecord.setText("Delete");
        btnDeleteRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRecordActionPerformed(evt);
            }
        });

        txtRoomPrice.setToolTipText("");

        lblRoomPrice.setLabelFor(txtRoomPrice);
        lblRoomPrice.setText("Room Price");

        lblRoomDescription.setLabelFor(txtRoomDescription);
        lblRoomDescription.setText("Room Description");

        lblMaxOccupancy.setLabelFor(txtMaxOccupancy);
        lblMaxOccupancy.setText("Room Max Occupancy");

        btnFindAction.setText("Find");
        btnFindAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionActionPerformed(evt);
            }
        });

        btnCreateCommit.setText("Create");
        btnCreateCommit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCommitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSearchCombo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboFacilityId, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFindByType, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReturn))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSearchID)
                        .addGap(4, 4, 4)
                        .addComponent(txtActionID, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblRoomNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                            .addComponent(lblHotelId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRoomType, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(txtRoomType))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cboHotelId, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtRoomNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRoomPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRoomDescription, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMaxOccupancy, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRoomPrice)
                            .addComponent(txtRoomDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(txtMaxOccupancy)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFindAction)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnCommitUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCreateCommit)
                .addGap(278, 278, 278)
                .addComponent(btnDeleteRecord))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReturn)
                    .addComponent(btnSearch)
                    .addComponent(btnDelete)
                    .addComponent(btnUpdate)
                    .addComponent(btnCreate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboFacilityId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFindByType)
                    .addComponent(lblSearchID)
                    .addComponent(txtActionID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearchCombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFindAction))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRoomNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRoomNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHotelId)
                            .addComponent(cboHotelId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRoomType)
                            .addComponent(txtRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRoomPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRoomPrice))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRoomDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRoomDescription))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaxOccupancy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaxOccupancy))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCommitUpdate)
                    .addComponent(btnDeleteRecord)
                    .addComponent(btnCreateCommit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        this.txtActionID.setText("");
        clearSubForm();
        this.populateHotel();
        
        setSubFormVisibility(false);
        this.clearTable(tblResults);
        setActionType("Update");
        
        this.lblSearchID.setVisible(true);
        this.txtActionID.setVisible(true);
        this.btnFindAction.setVisible(true);
        
        this.lblSearchCombo.setVisible(false);
        this.cboFacilityId.setVisible(false);
        this.btnFindByType.setVisible(false);
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
        getController().setView(new MainView(), this);
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        
        this.clearSubForm();
        clearTable(tblResults);
        setActionType("Create");
        setSubFormVisibility(true);
        this.populateHotel();
        
        this.lblSearchID.setVisible(false);
        this.txtActionID.setVisible(false);
        this.btnFindAction.setVisible(false);

        this.lblSearchCombo.setVisible(false);
        this.cboFacilityId.setVisible(false);
        this.btnFindByType.setVisible(false);
        
        this.btnCommitUpdate.setVisible(false);
        this.btnDeleteRecord.setVisible(false);
        this.btnCreateCommit.setVisible(true);
        
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        setSubFormVisibility(false);
        clearTable(tblResults);
        setActionType("Read");
        
        this.lblSearchCombo.setVisible(true);
        this.cboFacilityId.setVisible(true);
        this.btnFindByType.setVisible(true);
        
        populateComboBox();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnFindByTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindByTypeActionPerformed
        // TODO add your handling code here:
        try{
            
            ResultSet rset = null;
            
            tblResults.clearSelection();
            String[] tableColumnsName = {"Room Number","Hotel ID","Type","Price","Desciption","Max Occupancy"}; 
            DefaultTableModel aModel = (DefaultTableModel) tblResults.getModel();
            
            int rowCount = aModel.getRowCount();
            
            for (int i = rowCount - 1; i >= 0; i--) {
                aModel.removeRow(i);
            }
            
            aModel.setColumnIdentifiers(tableColumnsName);
            
            String selChoice = String.valueOf(this.cboFacilityId.getSelectedItem());
            
            if (selChoice.equals("All")){
                rset = getController().getModelBStatement().executeQuery ("Select * From Room");
            }
            else {
                rset = getController().getModelBStatement().executeQuery ("Select r.* From Room r, RoomFacility f where f.room_number = r.room_number And f.facility_number = '" + selChoice + "'");
            }
            
            
            // Loop through the ResultSet and transfer in the Model
            java.sql.ResultSetMetaData rsmd = rset.getMetaData();
            int colNo = rsmd.getColumnCount();
            while(rset.next()){
                Object[] objects = new Object[colNo];

                for(int i=0;i<colNo;i++){
                    objects[i]=rset.getObject(i+1);
                }
                
                aModel.addRow(objects);
            }
            
            tblResults.setModel(aModel);
            
            rset.close();
            
        }
        catch(Exception e){
            getController().showPopup("The query failed to execute!");
        }
    }//GEN-LAST:event_btnFindByTypeActionPerformed

    private void btnFindActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionActionPerformed
        // TODO add your handling code here:
        
        this.setSubFormVisibility(true);
        this.lblSearchCombo.setVisible(false);
        this.cboFacilityId.setVisible(false);
        this.btnFindByType.setVisible(false);
        
        try{
            
            ResultSet rset = null;
            String searchID = "";
            
            if (this.txtActionID.getText().trim().length() == 0){
                getController().showPopup("Room number is a required field.");
                this.setSubFormVisibility(false);
                this.setActionType("");
                return;
            }
            
            searchID = this.txtActionID.getText().trim();
            
            tblResults.clearSelection();
            String[] tableColumnsName = {"Room Number","Hotel ID","Type","Price","Desciption","Max Occupancy"}; 
            DefaultTableModel aModel = (DefaultTableModel) tblResults.getModel();
            
            int rowCount = aModel.getRowCount();
            
            for (int i = rowCount - 1; i >= 0; i--) {
                aModel.removeRow(i);
            }
            
            aModel.setColumnIdentifiers(tableColumnsName);
            
            rset = getController().getModelBStatement().executeQuery ("Select * From Room where Room_number = '" + searchID + "'");

            // Loop through the ResultSet and transfer in the Model
            java.sql.ResultSetMetaData rsmd = rset.getMetaData();
            int colNo = rsmd.getColumnCount();
            while(rset.next()){
                Object[] objects = new Object[colNo];

                for(int i=0;i<colNo;i++){
                    objects[i]=rset.getObject(i+1);
                }
                
                aModel.addRow(objects);
            }
            
            tblResults.setModel(aModel);

            rset.close();
            populateSubForm(searchID);
        }
        catch(Exception e){
            getController().showPopup("The query failed to execute!");
        }
        
    }//GEN-LAST:event_btnFindActionActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        this.txtActionID.setText("");
        clearSubForm();
        this.populateHotel();
        
        setSubFormVisibility(false);
        clearTable(tblResults);
        setActionType("Delete");
        
        this.lblSearchID.setVisible(true);
        this.txtActionID.setVisible(true);
        this.btnFindAction.setVisible(true);
        
        this.lblSearchCombo.setVisible(false);
        this.cboFacilityId.setVisible(false);
        this.btnFindByType.setVisible(false);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCreateCommitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCommitActionPerformed
        // TODO add your handling code here:
        
        ResultSet rset = null;
        
        if (!validateForm()){
            return;
        }
        
        try{
            rset = getController().getModelBStatement().executeQuery ("INSERT INTO Room Values ("
                                            + "'" + this.txtRoomNumber.getText().trim() + "', "
                                            + String.valueOf(this.cboHotelId.getSelectedItem()) 
                                            + ", '" + this.txtRoomType.getText().trim() 
                                            + "', " + this.txtRoomPrice.getText().trim()
                                            + ", '" + this.txtRoomDescription.getText().trim()
                                            + "', " + this.txtMaxOccupancy.getText().trim()
                                            + ")");
            getController().showPopup("Your Room has been created");
            
            this.clearSubForm();
            
            tblResults.clearSelection();
            String[] tableColumnsName = {"Room Number","Hotel ID","Type","Price","Desciption","Max Occupancy"}; 
            DefaultTableModel aModel = (DefaultTableModel) tblResults.getModel();
            
            int rowCount = aModel.getRowCount();
            
            for (int i = rowCount - 1; i >= 0; i--) {
                aModel.removeRow(i);
            }
            
            aModel.setColumnIdentifiers(tableColumnsName);
            
            rset = getController().getModelBStatement().executeQuery ("Select * From Room where Room_Number = '" + this.txtRoomNumber.getText().trim() + "'");

            // Loop through the ResultSet and transfer in the Model
            java.sql.ResultSetMetaData rsmd = rset.getMetaData();
            int colNo = rsmd.getColumnCount();
            while(rset.next()){
                Object[] objects = new Object[colNo];

                for(int i=0;i<colNo;i++){
                    objects[i]=rset.getObject(i+1);
                }
                
                aModel.addRow(objects);
            }
            
            tblResults.setModel(aModel);
            
            rset.close();

        }
        catch(Exception e){
            getController().showPopup(e.getMessage());
        }
    }//GEN-LAST:event_btnCreateCommitActionPerformed

    private void btnCommitUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommitUpdateActionPerformed
        // TODO add your handling code here:
        ResultSet rset = null;
        String strSQL = "";
        String searchID = "";
        
        if (!validateForm()){
            return;
        };
        
        
        if (this.txtActionID.getText().trim().length() == 0){
            getController().showPopup("Please enter a valid number");
            this.setSubFormVisibility(false);
            this.setActionType("");
            return;
        }
        

        searchID = this.txtActionID.getText().trim();

        strSQL = "Update Room ";
        strSQL += "SET Room_Number = '" + this.txtRoomNumber.getText().trim() + "', ";
        strSQL += "Hotel_ID = " + String.valueOf(this.cboHotelId.getSelectedItem()) + ",";
        strSQL += "Room_Type = '" + this.txtRoomType.getText().trim() + "',";
        strSQL += "Room_Price = " + this.txtRoomPrice.getText().trim() + ",";
        strSQL += "Room_Description = '" + this.txtRoomDescription.getText().trim() + "',";
        strSQL += "Room_Max_Occupancy = '" + this.txtMaxOccupancy.getText().trim() + "'";
        strSQL += "where Room_Number = '" + searchID + "'";
        
        try{
            rset = getController().getModelBStatement().executeQuery (strSQL);
            
            getController().showPopup("Your room has been updated");
            
            tblResults.clearSelection();
            String[] tableColumnsName = {"Room Number","Hotel ID","Type","Price","Desciption","Max Occupancy"}; 
            DefaultTableModel aModel = (DefaultTableModel) tblResults.getModel();
            
            int rowCount = aModel.getRowCount();
            
            for (int i = rowCount - 1; i >= 0; i--) {
                aModel.removeRow(i);
            }
            
            aModel.setColumnIdentifiers(tableColumnsName);
            
            rset = getController().getModelBStatement().executeQuery ("Select * From Room where room_number = '" + searchID + "'");

            // Loop through the ResultSet and transfer in the Model
            java.sql.ResultSetMetaData rsmd = rset.getMetaData();
            int colNo = rsmd.getColumnCount();
            while(rset.next()){
                Object[] objects = new Object[colNo];

                for(int i=0;i<colNo;i++){
                    objects[i]=rset.getObject(i+1);
                }
                
                aModel.addRow(objects);
            }
            
            tblResults.setModel(aModel);
            
            rset.close();
        }
        catch(Exception e){
            getController().showPopup(e.getMessage());
        }

    }//GEN-LAST:event_btnCommitUpdateActionPerformed

    private void btnDeleteRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRecordActionPerformed
        // TODO add your handling code here:
        
        String searchID = "";
        String strSQL = "";
        
        if (this.txtActionID.getText().trim().length() == 0){
            getController().showPopup("Please enter a valid number");
            this.setSubFormVisibility(false);
            this.setActionType("");
            return;
        }
        
        searchID = this.txtActionID.getText().trim();
        
        strSQL = "Delete FROM Room WHERE Room_Number = '" + searchID + "'";
        
        try{
            ResultSet rset = getController().getModelBStatement().executeQuery (strSQL);
        }
        catch(Exception e){
            getController().showPopup(e.getMessage());
        }
        
        try{
            ResultSet rset = getController().getModelBStatement().executeQuery ("Select * From Room where Room_number = '" + searchID + "'");
            getController().showPopup("Room Deleted");
        }
        catch(Exception e){
            getController().showPopup(e.getMessage());
        }
        
        this.txtActionID.setText("");
            
        this.clearTable(tblResults);
        setSubFormVisibility(false);
    }//GEN-LAST:event_btnDeleteRecordActionPerformed

    private void txtRoomNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoomNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoomNumberActionPerformed

    public void clearSubForm(){
        this.txtRoomNumber.setText("");
        if (this.cboHotelId.getItemCount() != 0){
            this.cboHotelId.setSelectedIndex(0);
        }
        this.txtRoomType.setText("");
        this.txtRoomPrice.setText("");
        this.txtRoomDescription.setText("");
        this.txtMaxOccupancy.setText("");
    }
    
    public void clearTable(JTable table){
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
    }
    
    public String getActionType(){
        return actionType;
    }
    
    public void populateComboBox(){
        try {
                this.cboFacilityId.removeAllItems();               
                
                this.cboFacilityId.addItem("All");
                
                ResultSet rset = getController().getModelBStatement().executeQuery("Select distinct Facility_Number from RoomFacility");
                while ( rset.next() ) {
                    this.cboFacilityId.addItem(rset.getString(1));
                }
                rset.close();
            }
            catch(SQLException f){
                getController().showPopup("error in connection");
            }
    }
    
    public void populateHotel(){
        try {
                this.cboHotelId.removeAllItems();               
                
                ResultSet rset = getController().getModelBStatement().executeQuery("Select distinct Hotel_ID from Hotel@FIT5148A");
                while ( rset.next() ) {
                    this.cboHotelId.addItem(rset.getString(1));
                }
                rset.close();
            }
            catch(SQLException f){
                getController().showPopup("error in connection");
            }
    }
    
    public void populateSubForm(String id){
        try{
            ResultSet rset = getController().getModelBStatement().executeQuery("Select * from room where room_number = '" + id + "'");
            while ( rset.next() ) {
                this.txtRoomNumber.setText(rset.getString(1));
                this.cboHotelId.setSelectedItem(rset.getString(2));
                this.txtRoomType.setText(rset.getString(3));
                this.txtRoomPrice.setText(rset.getString(4));
                this.txtRoomDescription.setText(rset.getString(5));
                this.txtMaxOccupancy.setText(rset.getString(6));
            }
            rset.close();
        }
        catch (Exception e){
            getController().showPopup(e.getMessage());
        }
    }
    
    public void setActionType(String newAct){
        actionType = newAct;
    }
    
    public void setSubFormVisibility(boolean newVis){
        
        this.lblSearchID.setVisible(newVis);
        this.txtActionID.setVisible(newVis);
        this.btnFindAction.setVisible(newVis);

        this.lblSearchCombo.setVisible(newVis);
        this.cboFacilityId.setVisible(newVis);
        this.btnFindByType.setVisible(newVis);
        
        this.lblRoomNumber.setVisible(newVis);
        this.txtRoomNumber.setVisible(newVis);
        
        this.lblHotelId.setVisible(newVis);
        this.cboHotelId.setVisible(newVis);
        
        this.lblRoomType.setVisible(newVis);
        this.txtRoomType.setVisible(newVis);
        
        this.lblRoomDescription.setVisible(newVis);
        this.txtRoomDescription.setVisible(newVis);
        
        this.lblRoomPrice.setVisible(newVis);
        this.txtRoomPrice.setVisible(newVis);
        
        this.lblMaxOccupancy.setVisible(newVis);
        this.txtMaxOccupancy.setVisible(newVis);
        
        if (newVis){
            if (this.getActionType().equals("Create")){
                this.btnCreateCommit.setVisible(newVis);
            }
            else if (this.getActionType().equals("Update")){
                this.btnCommitUpdate.setVisible(newVis);
            }
            else if (this.getActionType().equals("Delete")){
                this.btnDeleteRecord.setVisible(newVis);
            }
        }
        else {
            this.btnCommitUpdate.setVisible(newVis);
            this.btnDeleteRecord.setVisible(newVis);
            this.btnCreateCommit.setVisible(newVis);
        }
        
    }
    
    public boolean validateForm(){
        
        if (this.txtRoomType.getText().trim().length() == 0){
            getController().showPopup("Room Type is a required field!");
            return false;
        }
        
        else if (this.txtRoomPrice.getText().trim().length() == 0){
            getController().showPopup("Room price is a required field!");
            return false;
        }
        
        else if (this.txtRoomDescription.getText().trim().length() == 0){
            getController().showPopup("Room description is a required field!");
            return false;
        }
        
        else if (this.txtMaxOccupancy.getText().trim().length() == 0){
            getController().showPopup("Max Occupancy is a required field!");
            return false;
        }
        
        else {
            return true;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCommitUpdate;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnCreateCommit;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteRecord;
    private javax.swing.JButton btnFindAction;
    private javax.swing.JButton btnFindByType;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboFacilityId;
    private javax.swing.JComboBox<String> cboHotelId;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHotelId;
    private javax.swing.JLabel lblMaxOccupancy;
    private javax.swing.JLabel lblRoomDescription;
    private javax.swing.JLabel lblRoomNumber;
    private javax.swing.JLabel lblRoomPrice;
    private javax.swing.JLabel lblRoomType;
    private javax.swing.JLabel lblSearchCombo;
    private javax.swing.JLabel lblSearchID;
    private javax.swing.JTable tblResults;
    private javax.swing.JTextField txtActionID;
    private javax.swing.JTextField txtMaxOccupancy;
    private javax.swing.JTextField txtRoomDescription;
    private javax.swing.JTextField txtRoomNumber;
    private javax.swing.JTextField txtRoomPrice;
    private javax.swing.JTextField txtRoomType;
    // End of variables declaration//GEN-END:variables
}
